# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        rails-version: ['6.0.0', '6.1.0', '7.0.0']
        include:
          - ruby-version: 2.3.8
            rails-version: 3.2.0
          - ruby-version: 2.3.8
            rails-version: 4.0.0
          - ruby-version: 2.3.8
            rails-version: 4.1.0
          - ruby-version: 2.3.8
            rails-version: 4.2.0
          - ruby-version: 2.6.6
            rails-version: 5.0.0
          - ruby-version: 2.6.6
            rails-version: 5.1.0
          - ruby-version: 2.6.6
            rails-version: 5.2.0
          - ruby-version: 2.7.1
            rails-version: 6.0.0

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # See https://github.com/ruby/setup-ruby#versioning
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      env:
        RAILS_VERSION: ${{ matrix.rails-version }}
    - name: Run tests
      run: bundle exec rspec spec
      env:
        RAILS_VERSION: ${{ matrix.rails-version }}
